### ISSUE TITLE
Campath Integration

### ISSUE THREAD

**Issue by Devostated** [xNWP/HLAELiveLink#1]
Live modifying of ingame campath.
Create a campath ingame or C4D
Modify the campath live in C4D without any import/export
Have Fun And Record Your Clip

**Comment by xNWP** [comment]
Could you elaborate on how you would like the campath to be transposed into Cinema 4D, are you thinking each campath keyframe get's mapped into Cinema 4D, or are you thinking every individual point of the full campath is mapped into Cinema 4D (giving better accuracy to the ingame campath but making it more difficult to edit).

**Comment by Devostated** [comment]
thought about each campath keyframe get|s mapped into C4D, but that's abit inaccurate 
so idk we have to think about something

**Comment by xNWP** [comment]
Feel free to reopen once you figure out exactly the feature you'd like
